language: c
os: linux
script: TRAVIS_MODE=1 ./scripts/build-release preflight run_build_fresh run_distcheck_fast run_valgrind_fast
# Need all history to build change log.
git:
  depth: false
  quiet: true
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          gcc-4.9
      env:
        - MATRIX_EVAL="CC=gcc-4.9"
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          gcc-5
      env:
        - MATRIX_EVAL="CC=gcc-5"
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          gcc-6
      env:
        - MATRIX_EVAL="CC=gcc-6"
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          gcc-7
      env:
        - MATRIX_EVAL="CC=gcc-7"
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          gcc-8
      env:
        - MATRIX_EVAL="CC=gcc-8"
  - os: linux
    compiler:
      - clang
notifications:
  email:
    recipients:
    - rlk@alum.mit.edu
    on_success: always
    on_failure: always
addons:
  apt:
    packages:
    - autoconf
    - autogen
    - automake
    - autopoint
    - bison
    - bzip2
    - cups-filters
    - cups-filters-core-drivers
    - cups-client
    - docbook
    - docbook-dsssl
    - docbook-simple
    - docbook-utils
    - docbook-xml
    - docbook-xsl
    - doxygen
    - dvips-fontdata-n2bk
    - flex
    - gettext
    - imagemagick
    - jade
    - jadetex
    - libcups2-dev
    - libcupsimage2-dev
    - libgimp2.0-dev
    - libtool
    - libusb-1.0-0-dev
    - openjade
    - pdfjam
    - perl
    - sgml-base
    - sgml-data
    - sgmltools-lite
    - texi2html
    - time
    - valgrind
    - xz-utils
    - zpaq
