os: linux
language: c
os: linux
script: TRAVIS_MODE=1 ./scripts/build-release preflight run_build_fresh run_distcheck_fast run_valgrind_fast
# Need all history to build change log.
sources:
  - ubuntu-toolchain-r-test
  - llvm-toolchain-precise-3.8
  - llvm-toolchain-precise-4.0
  - llvm-toolchain-precise-5.0
git:
  depth: false
  quiet: true
matrix:
  include:
  - name: gcc-4.9
    env:
      - MATRIX_EVAL="CC=gcc-4.9"
  - name: gcc-5
    env:
      - MATRIX_EVAL="CC=gcc-5"
  - name: gcc-6
    env:
      - MATRIX_EVAL="CC=gcc-6"
  - name: gcc-7
    env:
      - MATRIX_EVAL="CC=gcc-7"
  - name: gcc-8
    env:
      - MATRIX_EVAL="CC=gcc-8"
  - name: clang-3.8
    env:
      - MATRIX_EVAL="CC=clang-3.8"
  - name: clang-4.0
    env:
      - MATRIX_EVAL="CC=clang-4.0"
  - name: clang-5.0
    env:
      - MATRIX_EVAL="CC=clang-5.0"
before_install:
  - eval "$(MATRIX_EVAL)"
notifications:
  email:
    recipients:
    - rlk@alum.mit.edu
    on_success: always
    on_failure: always
addons:
  apt:
    packages:
    - autoconf
    - autogen
    - automake
    - autopoint
    - bison
    - bzip2
    - cups-filters
    - cups-filters-core-drivers
    - cups-client
    - docbook
    - docbook-dsssl
    - docbook-simple
    - docbook-utils
    - docbook-xml
    - docbook-xsl
    - doxygen
    - dvips-fontdata-n2bk
    - flex
    - gettext
    - imagemagick
    - jade
    - jadetex
    - libcups2-dev
    - libcupsimage2-dev
    - libgimp2.0-dev
    - libtool
    - libusb-1.0-0-dev
    - openjade
    - pdfjam
    - perl
    - sgml-base
    - sgml-data
    - sgmltools-lite
    - texi2html
    - time
    - valgrind
    - xz-utils
    - zpaq
