language: c
script: BUILD_VERBOSE=1 ./scripts/build-release
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - autoconf
    - autogen
    - automake
    - autopoint
    - bison
    - bzip2
    - cups-client
    - docbook
    - docbook-dsssl
    - docbook-simple
    - docbook-utils
    - docbook-xml
    - docbook-xsl
    - doxygen
    - dvips-fontdata-n2bk
    - flex
    - gettext
    - imagemagick
    - jade
    - jadetex
    - libcups2-dev
    - libcupsimage2-dev
    - libtool
    - openjade
    - pdfjam
    - perl
    - sgml-base
    - sgml-data
    - sgmltools-lite
    - texi2html
    - time
    - valgrind
    - xz-utils
    - zpaq
