os: linux
language: c
sudo: required
# Need all history to build change log.
git:
  depth: false
  quiet: true
jobs:
  include:
    - stage: smoke test
      script: scripts/travis/smoke
    - stage: "integration tests"
      script: scripts/travis/integration gcc-4.9
    -
      script: scripts/travis/integration gcc-7
    -
      script: scripts/travis/integration gcc-8
    -
      script: scripts/travis/integration clang-3.8
    - stage: checksums
      script: scripts/travis/checksums 0 7
    -
      script: scripts/travis/checksums 1 7
    -
      script: scripts/travis/checksums 2 7
    -
      script: scripts/travis/checksums 3 7
    -
      script: scripts/travis/checksums 4 7
    -
      script: scripts/travis/checksums 5 7
    -
      script: scripts/travis/checksums 6 7
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
notifications:
  email:
    recipients:
      - rlk@alum.mit.edu
    on_success: always
    on_failure: always
